var tree = [["VirtualFileSystem","VirtualFileSystem.html","",
                [["Structure","VirtualFileSystem\/Structure.html","",
                [["Directory","VirtualFileSystem\/Structure\/Directory.html"," < Node",
                [        ]],["File","VirtualFileSystem\/Structure\/File.html"," < Node",
                [        ]],["Link","VirtualFileSystem\/Structure\/Link.html"," < Node",
                [        ]],["Node","VirtualFileSystem\/Structure\/Node.html","",
                [        ]],["Root","VirtualFileSystem\/Structure\/Root.html"," < Directory",
                [        ]]        ]],["Wrapper","VirtualFileSystem\/Wrapper.html","",
                [["DirectoryHandler","VirtualFileSystem\/Wrapper\/DirectoryHandler.html","",
                [        ]],["FileHandler","VirtualFileSystem\/Wrapper\/FileHandler.html","",
                [        ]],["PermissionHelper","VirtualFileSystem\/Wrapper\/PermissionHelper.html","",
                [        ]]        ]],["Container","VirtualFileSystem\/Container.html","",
                [        ]],["Factory","VirtualFileSystem\/Factory.html","",
                [        ]],["FileExistsException","VirtualFileSystem\/FileExistsException.html"," < Exception",
                [        ]],["FileSystem","VirtualFileSystem\/FileSystem.html","",
                [        ]],["Loader","VirtualFileSystem\/Loader.html","",
                [        ]],["NotFoundException","VirtualFileSystem\/NotFoundException.html"," < Exception",
                [        ]],["Wrapper","VirtualFileSystem\/Wrapper.html","",
                [        ]]        ]]        ]

